//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.01.15 at 11:43:19 AM EST
//


package com.healthmarketscience.jackcess.crypt.model.cert;

/**
 * <p>Java class for CT_CertificateKeyEncryptor complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CT_CertificateKeyEncryptor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="encryptedKeyValue" use="required" type="{http://www.w3.org/2001/XMLSchema}base64Binary" />
 *       &lt;attribute name="X509Certificate" use="required" type="{http://www.w3.org/2001/XMLSchema}base64Binary" />
 *       &lt;attribute name="certVerifier" use="required" type="{http://www.w3.org/2001/XMLSchema}base64Binary" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
// @XmlAccessorType(XmlAccessType.FIELD)
// @XmlType(name = "CT_CertificateKeyEncryptor")
public class CTCertificateKeyEncryptor {

    // @XmlAttribute(required = true)
    protected byte[] encryptedKeyValue;
    // @XmlAttribute(name = "X509Certificate", required = true)
    protected byte[] x509Certificate;
    // @XmlAttribute(required = true)
    protected byte[] certVerifier;

    /**
     * Gets the value of the encryptedKeyValue property.
     *
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getEncryptedKeyValue() {
        return encryptedKeyValue;
    }

    /**
     * Sets the value of the encryptedKeyValue property.
     *
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setEncryptedKeyValue(byte[] value) {
        this.encryptedKeyValue = ((byte[]) value);
    }

    /**
     * Gets the value of the x509Certificate property.
     *
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getX509Certificate() {
        return x509Certificate;
    }

    /**
     * Sets the value of the x509Certificate property.
     *
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setX509Certificate(byte[] value) {
        this.x509Certificate = ((byte[]) value);
    }

    /**
     * Gets the value of the certVerifier property.
     *
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getCertVerifier() {
        return certVerifier;
    }

    /**
     * Sets the value of the certVerifier property.
     *
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setCertVerifier(byte[] value) {
        this.certVerifier = ((byte[]) value);
    }

}
