//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.01.15 at 11:43:19 AM EST
//


package com.healthmarketscience.jackcess.crypt.model.cert;

/**
 * <p>Java class for ST_CertificateKeyEncryptorUri.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ST_CertificateKeyEncryptorUri">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="http://schemas.microsoft.com/office/2006/keyEncryptor/certificate"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
// @XmlType(name = "ST_CertificateKeyEncryptorUri")
// @XmlEnum
public enum STCertificateKeyEncryptorUri {

    // @XmlEnumValue("http://schemas.microsoft.com/office/2006/keyEncryptor/certificate")
    HTTP_SCHEMAS_MICROSOFT_COM_OFFICE_2006_KEY_ENCRYPTOR_CERTIFICATE("http://schemas.microsoft.com/office/2006/keyEncryptor/certificate");
    private final String value;

    STCertificateKeyEncryptorUri(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static STCertificateKeyEncryptorUri fromValue(String v) {
        for (STCertificateKeyEncryptorUri c: STCertificateKeyEncryptorUri.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
